source 'https://rubygems.org'

gem 'totally_lazy'
gem 'lazy_records'
gem 'oj'
gem 'sinatra'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'sqlite3'
gem 'bcrypt-ruby'
gem 'rack_csrf'
gem 'encrypted_cookie'
gem 'thin'

group :development do
  gem 'activerecord'
  gem 'railties'
  gem 'standalone_migrations'
  gem 'rake'
  gem 'rspec'
  gem 'rack-test'
end


